Repository POFECT/Factory-Decision-System, pull requests merged in 2023-12, with the labels that each got.

#6 [Feat] entity 최종임
  backend/src/main/java/com/poscodx/pofect/domain/entity/AdminByItemType.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/BaseEntity.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/BusinessCodeInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/CapacityInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/ConfirmFactoryStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/EssentialStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/FactorySizeStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/GrantCapacity.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/MainProcessCode.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/PossibleFactoryStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/ProcessStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/entity/User.java
  backend/src/main/java/com/poscodx/pofect/domain/main/entity/FactoryOrderInfo.java
Labels: 백엔드, 개발환경 세팅

#7 [style] essential
  frontend/src/@core/theme/overrides/button.js
  frontend/src/pages/a/index.js
  frontend/src/pages/account-settings/index.js
  frontend/src/pages/essential-goods/index.js
  frontend/src/pages/input-capacity/index.js
Labels: 프론트엔드, UI/UX

#9 [feat] datat grid
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/a/index.js
  frontend/src/pages/grid-test/index.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX

#10 [chore] 필수재 엔티티 최종 수정
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/EssentialStandard.java
Labels: 백엔드, 개발환경 세팅

#12 [FEAT] 가능/확통기준 가능통과코드 전체 GET API
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleFactoryStandardReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/entity/ConfirmFactoryStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/entity/PossibleFactoryStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/PossibleFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/factory-standard/index.js
  frontend/yarn.lock
Labels: 백엔드, 기능개발

#14 [feat] 투입능관리 api-GET commit
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CapacityInfoDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CombinedCapacityDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/GrantCapacityDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/entity/CapacityInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/entity/GrantCapacity.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityInfoRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/GrantCapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
Labels: 백엔드, 기능개발

#16 [faet] 필수재 기준 조회 api
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/EssentialStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/controller/EssentialStandardController.java
Labels: 백엔드, 기능개발

#17 [Feat] entity 컬럼 수정
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/entity/FactoryOrderInfo.java
Labels: 백엔드, 개발환경 세팅

#18 [bug] navigation
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/size-standard/index.js
  frontend/yarn.lock
Labels: 버그, 프론트엔드

#67 [Feat] axios 모듈화, 가통설계 화면
  frontend/src/api/MainCapacityApi.js
  frontend/src/api/api.js
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/main-capacity/capacity-detail.js
  frontend/src/pages/main-capacity/index.js
Labels: 프론트엔드, UI/UX, 개발환경 세팅

#71 [feat] 필수재 기준 ui 추가
  frontend/src/api/EssentialStandardApi.js
  frontend/src/pages/essential-goods/index.js
Labels: 프론트엔드, UI/UX

#73 [feat] 대시보드 품종 별 투입 현황 GET API
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/.gitkeep
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/controller/DashBoardController.java
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/dto/DashBoardInputStatusResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/service/DashBoardService.java
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/service/DashBoardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/FactoryOrderInfoRepository.java
Labels: 백엔드, 기능개발

#74 [feat] 사이즈 기준 GET API 연동
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/ConfirmFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/ConfirmFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/ConfirmFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardService.java
  frontend/src/api/SizeStandardApi.js
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/size-standard/index.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX, 기능개발

#76 [Feat]가통/확통코드 가통 Grid맞춤 GET API 및 UI개발 + Git 충돌해결
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/ConfirmFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/ConfirmFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/ConfirmFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/PossibleFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  frontend/src/api/FactoryStandardApi.js
  frontend/src/pages/factory-standard/index.js
Labels: 버그, 프론트엔드, 백엔드, 기능개발

#78 [fix] 충돌로인한 domain/passstandard 부분 오류 수정
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/ConfirmFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/ConfirmFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  frontend/yarn.lock
Labels: 버그, 백엔드

#79 [Feat] selectbox 품종 API 개발 및 연결, 엔티티 수정
  backend/src/main/java/com/poscodx/pofect/domain/capacity/entity/CapacityInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/entity/GrantCapacity.java
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/dto/DashBoardInputStatusResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/dto/EssentialStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/entity/EssentialStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/controller/EtcController.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/dto/BusinessCodeInfoDto.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/entity/AdminByItemType.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/entity/BaseEntity.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/entity/BusinessCodeInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/entity/MainProcessCode.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/repository/BusinessCodeInfoRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/service/BusinessCodeInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/service/BusinessCodeInfoServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/entity/FactoryOrderInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/entity/ConfirmFactoryStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/entity/PossibleFactoryStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/ProcessStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/FactorySizeStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/user/User.java
  frontend/src/api/MainCapacityApi.js
  frontend/src/pages/main-capacity/capacity-detail.js
  frontend/src/pages/main-capacity/index.js
Labels: 프론트엔드, 백엔드, 개발환경 세팅, 기능개발

#80 [Feat/Fix] capacity data 구성, 충돌 fix
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/GrantCapacityDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/entity/GrantCapacity.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/GrantCapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
Labels: 버그, 백엔드, 기능개발

#81 [feat] 대시보드 품종 별 주문조회 GET API 구현
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/controller/DashBoardController.java
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/dto/DashBoardOrderInquiryResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/service/DashBoardService.java
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/service/DashBoardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/FactoryOrderInfoRepository.java
Labels: 백엔드, 기능개발

#84 [FEAT/FIX] 경유공정기준 백앤드 에러 수정
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/ProcessStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/dto/ProcessStandardDto.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/entity/ProcessStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/repository/ProcessStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
Labels: 버그, 백엔드

#85 [feat] 대시보드 주문 조회 UI
  frontend/src/@core/theme/ThemeOptions.js
  frontend/src/api/DashBoardApi.js
  frontend/src/api/DashBoardInputStatus.js
  frontend/src/pages/capacity/modal-test.js
  frontend/src/pages/dashboard/index.js
  frontend/styles/globals.css
Labels: 프론트엔드, UI/UX

#87 [FEAT] Lot 화면 구현
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/controller/SizeStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/RowSpan.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/SizeStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/entity/FactorySizeStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/repository/SizeStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX

#89 [feat] passStandard & navibar modified
  frontend/src/api/CapacityApi.js
  frontend/src/api/PassStandardApi.js
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/capacity/index.js
  frontend/src/pages/pass-standard/index.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX, 디자인

#90 [feat] navibar modified
  frontend/src/navigation/vertical/index.js
Labels: UI/UX

#92 Feat fe/pass standard
  frontend/src/api/CapacityApi.js
  frontend/src/api/PassStandardApi.js
  frontend/src/pages/capacity/index.js
  frontend/src/pages/pass-standard/index.js
Labels: 프론트엔드, UI/UX

#93 [Feat]가통/확통기준 grid data 완료
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/ConfirmFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/ConfirmFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  frontend/src/api/FactoryStandardApi.js
  frontend/src/pages/factory-standard/index.js
Labels: 프론트엔드, 백엔드, 기능개발

#94 [feat] navigation 수정
  frontend/src/@core/layouts/components/vertical/navigation/VerticalNavHeader.js
  frontend/src/@core/layouts/components/vertical/navigation/VerticalNavItems.js
  frontend/src/@core/layouts/components/vertical/navigation/VerticalNavLink.js
  frontend/src/@core/layouts/components/vertical/navigation/VerticalNavSectionTitle.js
  frontend/src/@core/layouts/components/vertical/navigation/index.js
  frontend/src/navigation/vertical/index.js
  frontend/styles/globals.css
Labels: 프론트엔드, 기능개발

#95 [FEAT] 출강Lot 및 사이즈 기준 UI 변경
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/RowSpan.java
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
  package.json
Labels: 프론트엔드, 백엔드, UI/UX

#96 [FEAT] 사이즈 기준 rowSpan 수정
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/RowSpan.java
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
Labels: 백엔드

#97 [feat] grid 수정
  frontend/src/pages/essential-goods/index.js
Labels: 프론트엔드, UI/UX, 기능개발

#98 [Feat] queryDSL 설정 & 출강주 조회 API 구현
  backend/build.gradle
  backend/src/main/java/com/poscodx/pofect/common/querydsl/DefaultCondition.java
  backend/src/main/java/com/poscodx/pofect/common/querydsl/Querydsl4RepositorySupport.java
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/FactoryOrderInfoRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/condition/FactoryOrderInfoCondition.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
Labels: 백엔드, 개발환경 세팅, 기능개발

#99 [feat] modal test
  frontend/public/images/img.gif
  frontend/src/pages/dashboard-ref/index.js
  frontend/src/pages/essential-goods-ref/index.js
  frontend/src/pages/grid-test/index.js
  frontend/src/pages/input-capacity-ref/index.js
  frontend/src/pages/lot/index.js
  frontend/src/pages/modal/index.js
Labels: 프론트엔드, UI/UX, 기능개발

#100 [feat] passstandard modified
  frontend/src/api/CapacityApi.js
  frontend/src/api/PassStandardApi.js
  frontend/src/pages/capacity/chart.js
  frontend/src/pages/capacity/index.js
  frontend/src/pages/pass-standard/index.js
Labels: 프론트엔드, UI/UX

#101 [Style] 출강Lot 테이블 화면 변경
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
Labels: 프론트엔드, UI/UX

#103 [chore] FactoryOrderInfo column 추가
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/entity/FactoryOrderInfo.java
Labels: 백엔드, 개발환경 세팅

#104 [feat] 필수재 박판공정계획 필터링 추가
  frontend/src/pages/essential-goods/index.js
Labels: 프론트엔드, 기능개발

#105 [Feat] 주문조회 API
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/condition/FactoryOrderInfoCondition.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/ConfirmFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/ConfirmFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/ConfirmFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardServiceImpl.java
  frontend/src/api/MainCapacityApi.js
  frontend/src/pages/main-capacity/capacity-detail.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/factory-detail.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/pages/main-confirm/order-detail.js
Labels: 백엔드, 기능개발

#106 [Feat] 출강주 API 연결
  frontend/src/api/MainCapacityApi.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/pages/main-confirm/order-detail.js
Labels: 프론트엔드, UI/UX

#107 [UI/UX]가능/확통기준 - 가통 코드상세 Popper 개발
  frontend/src/api/FactoryStandardApi.js
  frontend/src/pages/factory-standard/index.js
  frontend/src/pages/factory-standard/possible-detail.js
  frontend/yarn-error.log
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX, 기능개발

#108 [Feat] capacity 백엔드 메소드 구현
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CapacityInfoDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CombinedCapacityDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/GrantCapacityDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/entity/CapacityInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/entity/GrantCapacity.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityInfoRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/GrantCapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
Labels: 백엔드, 기능개발

#110 [feat] passstandard modified
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/CapacityApi.js
  frontend/src/pages/capacity/index.js
  frontend/src/pages/pass-standard/index.js
Labels: 프론트엔드, UI/UX

#111 [Feat] 주문리스트 필터링
  frontend/src/api/MainCapacityApi.js
  frontend/src/pages/main-capacity/capacity-detail.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
Labels: 프론트엔드, UI/UX, 기능개발

#112 [style] 가능/확통기준 Popper 90%완성
  frontend/src/api/FactoryStandardApi.js
  frontend/src/pages/factory-standard/index.js
  frontend/src/pages/factory-standard/possible-detail.js
Labels: 프론트엔드, UI/UX

#113 [Feat] 주문 별 사이즈 기준 로직 구현
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/controller/SizeStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/SizeStandardSetDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/factoryOrderInfo/FactoryOrderInfoResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/repository/SizeStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/repository/condition/SizeStandardCondition.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/repository/querydsl/SizeStandardCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/repository/querydsl/SizeStandardCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
Labels: 백엔드, 기능개발

#114 [sytle] 경유공정기준 page > popup 으로 이동
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/factory-standard/index.js
  frontend/src/pages/factory-standard/pass-modal.js
Labels: 프론트엔드, UI/UX

#115 [update] 백엔드 경유공정기준(passStandard)과 가능확통기준(processStandard) 패키지 위치 변경
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/ProcessStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/ProcessStandardDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/entity/ProcessStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/ProcessStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ProcessStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ProcessStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/ConfirmFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/dto/ConfirmFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/dto/PossibleFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/entity/ConfirmFactoryStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/entity/PossibleFactoryStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/repository/ConfirmFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/repository/PossibleFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ConfirmFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ConfirmFactoryStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/PossibleFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/PossibleFactoryStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/controller/SizeStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
Labels: 버그, 개발환경 세팅

#117 [Feat] 해당 공정의 공장리스트, 능력데이터 조회 API
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/pages/main-confirm/order-detail.js
Labels: 백엔드, 기능개발

#129 [Feat] 공장결정 제조투입 버튼 연결
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CapacityInfoDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/condition/FactoryOrderInfoCondition.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/ConfirmFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardServiceImpl.java
  frontend/src/api/MainCapacityApi.js
  frontend/src/pages/main-confirm/factory-detail.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/pages/main-confirm/order-detail.js
Labels: 프론트엔드, UI/UX

#130 [Feat] 플래그 변경 API 구현
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CapacityInfoDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/condition/FactoryOrderInfoCondition.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/ConfirmFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardServiceImpl.java
  frontend/src/api/MainCapacityApi.js
  frontend/src/pages/main-confirm/factory-detail.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/pages/main-confirm/order-detail.js
Labels: 백엔드, 기능개발

#133 [Feat] 주문리스트 조회, status 변경 API
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
  frontend/yarn.lock
Labels: 백엔드, 기능개발

#137 [Feat] be/capacity rowspan 구현
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CapacityInfoDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CombinedCapacityDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/GrantCapacityDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  frontend/src/api/CapacityApi.js
  frontend/src/pages/capacity/index.js
Labels: 백엔드, 기능개발

#141 [Feat] 경유공정 GET by 품명 api 추가
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/ProcessStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/dto/ProcessStandardDto.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/repository/ProcessStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
Labels: 백엔드, 기능개발

#142 [feat] 필수재기준 API 구현
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/controller/EssentialStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/dto/EssentialStandardBtiPosReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/dto/EssentialStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/dto/EssentialStandardSetDto.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/service/EssentialStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/service/EssentialStandardServiceImpl.java
  frontend/src/pages/essential-goods/index.js
Labels: 백엔드, 기능개발

#143 [Bug] be/capacity import 추가
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
Labels: 버그, 백엔드

#146 [Feat] 출강Lot 전체 GET API 구현
  backend/src/main/java/com/poscodx/pofect/domain/lot/controller/LotController.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotGroupDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotService.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/lot/LotResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/SizeStandardSetDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
Labels: 백엔드, 기능개발

#147 [Feat] fe/capacity 히트맵 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/capacity/chart.js
  frontend/src/pages/capacity/heat.js
  frontend/src/pages/capacity/index.js
Labels: 프론트엔드, UI/UX

#148 [feat]공장결정 - 주문 단위 결과 조정 UI 수정
  frontend/src/pages/main-confirm/factory-detail.js
  frontend/src/pages/main-confirm/order-detail.js
Labels: 프론트엔드, UI/UX, 기능개발

#149 [style]login화면 UI변경
  frontend/src/pages/login&userInfo/login/index.js
Labels: 프론트엔드, UI/UX

#153 [feat] data to excel 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/essential-goods/index.js
  frontend/yarn.lock
Labels: 프론트엔드, 기능개발

#154 [feat] 경유공정 품종 필터링 구현
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/ProcessStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/repository/ProcessStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
  frontend/src/api/PassStandardApi.js
  frontend/src/pages/factory-standard/pass-modal.js
  frontend/src/pages/pass-standard/index.js
Labels: 프론트엔드, UI/UX

#155 [feat]가통코드로 확통 공장 번호 반환
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/controller/EssentialStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleToConfirmResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/PossibleFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
Labels: 백엔드, 기능개발

#156 [feat] 대시보드 ui 수정
  frontend/src/@core/theme/typography/index.js
  frontend/src/pages/dashboard/index.js
  frontend/src/pages/index.js
  frontend/src/views/dashboard/Trophy.js
Labels: 프론트엔드, UI/UX

#158 [feat] 랜더링 시 스피너추가
  frontend/src/layouts/UserLayout.js
  frontend/src/views/spinners/Spinner.js
Labels: 프론트엔드, 기능개발

#160 [feat] 필수재기준 공장 코드 API
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/controller/EssentialStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/dto/EssentialStandardSetDto.java
Labels: 백엔드, 기능개발

#163 [style]UserInfo UI 개발
  frontend/public/images/login/upload-image-bg-gray.png
  frontend/public/images/login/upload-image-transparent.png
  frontend/src/pages/login&userInfo/userInfo/index.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX

#164 [bug] 필수재 기준
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/service/EssentialStandardServiceImpl.java
  frontend/yarn.lock
Labels: 버그, 백엔드, 기능개발

#165 [Feat] fe/capacity 투입산정 차트
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/capacity/heat.js
  frontend/src/pages/capacity/index.js
  frontend/src/pages/factory-standard/pass-modal.js
Labels: 버그, 프론트엔드, UI/UX

#166 [Bug] 능력 버그
  frontend/src/pages/capacity/d3-heat.js
Labels: UI/UX

#168 [feat] 출강Lot 기본 전체 GET API 구현
  backend/src/main/java/com/poscodx/pofect/domain/lot/controller/LotController.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotGroupDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotService.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/RowSpan.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  frontend/src/api/LotApi.js
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
Labels: 백엔드, 기능개발

#167 [feat] 출강Lot 기본 전체 GET API 연동
  backend/src/main/java/com/poscodx/pofect/domain/lot/controller/LotController.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotGroupDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotService.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/RowSpan.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  frontend/src/api/LotApi.js
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
Labels: 프론트엔드, 기능개발

#170 [feat] 헤더 수정
  frontend/src/@core/layouts/components/shared-components/ModeToggler.js
  frontend/src/@core/layouts/components/shared-components/NotificationDropdown.js
  frontend/src/@core/layouts/components/vertical/appBar/index.js
  frontend/src/@core/theme/typography/index.js
  frontend/src/pages/essential-goods/index.js
Labels: 프론트엔드, UI/UX

#172 [style]가능/확통기준 UI통일성을 위한 표 실선 + 엑셀기능추가
  frontend/src/pages/factory-standard/confirm-detail.js
  frontend/src/pages/factory-standard/index.js
Labels: 프론트엔드, UI/UX

#173 [Feat] 확통설계, 공장결정 API 완성
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CapacityInfoDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/entity/CapacityInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/controller/EssentialStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/passstandard/PossibleToConfirmResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/standard/SizeStandardSetDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/entity/FactoryOrderInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/PossibleFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/ProcessStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
Labels: 백엔드, 기능개발

#175 [Feat] fe/capacity 차트 레전드 추가 및 label추가, excel 추가
  frontend/src/pages/capacity/d3-heat.js
  frontend/src/pages/capacity/index.js
Labels: 프론트엔드, UI/UX

#176 [feat] 필수재기준 필터링
  frontend/src/api/EssentialStandardApi.js
  frontend/src/pages/essential-goods/index.js
Labels: 프론트엔드, 기능개발

#177 [Feat] 가통설계, 공장결정 API 연결
  frontend/src/api/MainApi.js
  frontend/src/pages/main-capacity/capacity-detail.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/factory-detail.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/pages/main-confirm/order-detail.js
Labels: 프론트엔드, UI/UX, 기능개발

#178 [feat] update API develop
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  frontend/src/pages/capacity/index.js
Labels: 백엔드, 기능개발

#179 [feat]엑셀 다운로드 기능에서 데이터 순서 변경 및 헤더 한글 적용
  frontend/src/pages/factory-standard/index.js
  frontend/src/pages/factory-standard/possible-detail.js
Labels: 프론트엔드, 기능개발

#180 [feat] spinner 수정
  frontend/src/views/spinners/Spinner.js
Labels: 프론트엔드, UI/UX

#181 [Feat] 날짜 format 변경
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/GrantCapacityDto.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/dto/EssentialStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/ConfirmFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/dto/ProcessStandardDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/SizeStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/factoryOrderInfo/FactoryOrderInfoResDto.java
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
Labels: 프론트엔드, 백엔드, UI/UX

#182 [Feat] 날짜 format 변경
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/GrantCapacityDto.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/dto/EssentialStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/ConfirmFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/dto/ProcessStandardDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/SizeStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/factoryOrderInfo/FactoryOrderInfoResDto.java
Labels: UI/UX

#183 [feat]가통 popper 체크 여부 보여주기
  frontend/src/pages/factory-standard/index.js
  frontend/src/pages/factory-standard/possible-detail.js
Labels: 프론트엔드, 기능개발

#184 [feat] 필수재 기준 UI 변경
  frontend/src/@core/theme/ThemeOptions.js
  frontend/src/@core/theme/typography/index.js
  frontend/src/pages/essential-goods/index.js
  frontend/styles/globals.css
Labels: 프론트엔드, UI/UX

#185 [style] 화면 통일 (버튼색상) & 가통 Popper 디자인 변경
  frontend/src/pages/factory-standard/index.js
  frontend/src/pages/factory-standard/pass-modal.js
  frontend/src/pages/factory-standard/possible-detail.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX

#186 [feat] 헤더 수정
  frontend/src/@core/layouts/VerticalLayout.js
  frontend/src/@core/layouts/components/shared-components/footer/FooterContent.js
  frontend/src/@core/layouts/components/vertical/appBar/index.js
  frontend/src/layouts/components/vertical/AppBarContent.js
Labels: 프론트엔드, UI/UX, 기능개발

#187 [style] 출강Lot UI 변경
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/controller/SizeStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/SizeStandardReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/SizeStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/entity/FactorySizeStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  frontend/src/api/SizeStandardApi.js
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
Labels: 프론트엔드, UI/UX

#188 [style] 가통설계, 공장결정 CSS
  frontend/src/pages/main-capacity/capacity-detail.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/factory-detail.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/pages/main-confirm/order-detail.js
Labels: 프론트엔드, UI/UX

#189 [feat] 투입능력 front develop
  frontend/src/api/CapacityApi.js
  frontend/src/pages/capacity/d3-heat.js
  frontend/src/pages/capacity/index.js
Labels: 프론트엔드, UI/UX

#190 [style]경유공정기준 그리드 헤더 추가
  frontend/src/pages/factory-standard/pass-modal.js
Labels: 프론트엔드, UI/UX

#191 [style] 진행단계 이름 변경
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
Labels: UI/UX

#192 [feat]login 시 가능통과공장설계 페이지로 이동
  frontend/src/pages/login&userInfo/login/index.js
Labels: 프론트엔드

#193 [feat] 주문리스트 Flag 필터링 적용
  frontend/src/pages/main-capacity/capacity-detail.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/pages/main-confirm/order-detail.js
Labels: 프론트엔드, UI/UX, 기능개발

#194 [feat] navigation, title 수정
  frontend/documentation.html
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/_app.js
Labels: 프론트엔드, UI/UX

#195 [Feat] 출강Lot 기투입 check
  backend/src/main/java/com/poscodx/pofect/domain/lot/controller/LotController.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotSearchDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotService.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
Labels: 프론트엔드, UI/UX

#196 [feat] 출강 Lot 출강주 별 검색 로직 구현
  backend/src/main/java/com/poscodx/pofect/domain/lot/controller/LotController.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotSearchDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotService.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
Labels: 백엔드, 기능개발

#197 [feat] 투입능력 front 차트 수정
  frontend/src/pages/capacity/d3-heat.js
Labels: 프론트엔드, UI/UX

#198 [feat] 출강주 별 검색 연동
  frontend/src/api/LotApi.js
  frontend/src/pages/lot/index.js
Labels: 프론트엔드, 기능개발

#224 [feat] 출강Lot 강종별, 품종별 GET API 구현
  backend/src/main/java/com/poscodx/pofect/domain/lot/controller/LotController.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotSearchDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/condition/FactoryOrderInfoCondition.java
  frontend/src/api/LotApi.js
  frontend/src/pages/lot/index.js
Labels: 백엔드, 기능개발

#225 [feat] 출강Lot 강종별, 품종별 검색 화면 연동
  backend/src/main/java/com/poscodx/pofect/domain/lot/controller/LotController.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/dto/LotSearchDto.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/condition/FactoryOrderInfoCondition.java
  frontend/src/api/LotApi.js
  frontend/src/pages/lot/index.js
Labels: 프론트엔드, 기능개발

#226 [feat]가능확통기준 가통Popper checked 가능하도록 변경
  frontend/src/api/FactoryStandardApi.js
  frontend/src/pages/factory-standard/possible-detail.js
Labels: 프론트엔드, 기능개발

#227 [Feat] 가통설계 상세페이지
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/passstandard/ConfirmFactoryStandardResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/entity/FactoryOrderInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/ConfirmFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/ConfirmFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/ConfirmFactoryStandardServiceImpl.java
  frontend/src/pages/main-capacity/capacity-detail.js
Labels: 프론트엔드, 백엔드, UI/UX, 기능개발

#228 [Feat] be/capacity 수정 기능 개발
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  frontend/src/api/CapacityApi.js
  frontend/src/pages/capacity/index.js
Labels: 백엔드, 기능개발

#229 [Feat] 대시보드 UI 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/dashboard/index.js
  frontend/src/views/dashboard/HeatMap.js
  frontend/src/views/dashboard/WeeklyHeatMap.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX, 기능개발

#230 [Feat] 대시보드 컴포넌트 분리 및 url 수정
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/dashboard/index.js
  frontend/src/pages/index.js
  frontend/src/views/dashboard/DepositWithdraw.js
  frontend/src/views/dashboard/FactoryGuage.js
  frontend/src/views/dashboard/HeatMap.js
  frontend/src/views/dashboard/InputStatusBar.js
  frontend/src/views/dashboard/OrderGrid.js
  frontend/src/views/dashboard/SalesByCountries.js
  frontend/src/views/dashboard/StatisticsCard.js
  frontend/src/views/dashboard/Table.js
  frontend/src/views/dashboard/TotalEarning.js
  frontend/src/views/dashboard/Trophy.js
  frontend/src/views/dashboard/WeeklyHeatMap.js
  frontend/src/views/dashboard/WeeklyOverview.js
Labels: 프론트엔드, UI/UX, 기능개발

#232 [feat] 사이즈 기준 예상 설계 API 구현
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/controller/SizeStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/SizeDesignReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  frontend/src/api/SizeStandardApi.js
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
  frontend/src/pages/size-standard/size-design-modal.js
  frontend/yarn.lock
Labels: 백엔드, 기능개발

#231 [feat] 사이즈 기준 예상 설계 화면 구현
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/controller/SizeStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/dto/SizeDesignReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  frontend/src/api/SizeStandardApi.js
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
  frontend/src/pages/size-standard/size-design-modal.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX, 기능개발

#233 [Feat] 경유공정 수정 api 구현 및 front 연동
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/ProcessStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/repository/ProcessStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
  frontend/src/api/PassStandardApi.js
  frontend/src/pages/factory-standard/pass-modal.js
Labels: 백엔드, 기능개발

#234 [feat] 대시보드 수정
  frontend/src/pages/index.js
  frontend/src/views/dashboard/FactoryGuage.js
  frontend/src/views/dashboard/HeatMap.js
  frontend/src/views/dashboard/InputStatusBar.js
  frontend/src/views/dashboard/OrderGrid.js
  frontend/src/views/dashboard/Throphy.js
  frontend/src/views/dashboard/WeeklyHeatMap.js
Labels: 프론트엔드, 기능개발

#236 [feat]가통코드기준 Popper 변경 API 개발
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleChangeReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/dto/PossibleChangeResultResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/repository/PossibleFactoryStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  frontend/src/api/FactoryStandardApi.js
  frontend/src/pages/factory-standard/index.js
  frontend/src/views/factory-standard/confirm-detail.js
  frontend/src/views/factory-standard/pass-modal.js
  frontend/src/views/factory-standard/possible-detail.js
Labels: 프론트엔드, 리팩토링, 백엔드, UI/UX, 기능개발

#241 [feat] 가통기준 저장후 새로고침 기능 추가
  frontend/src/views/factory-standard/possible-detail.js
Labels: 프론트엔드, 기능개발

#242 [Feat] 공장결정 API 및 사이즈기준 로직 변경
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/entity/CapacityInfo.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/src/api/MainApi.js
  frontend/src/pages/lot/index.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/factory-detail.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/pages/main-confirm/order-detail.js
  frontend/src/pages/size-standard/index.js
  frontend/src/views/main-capacity/capacity-detail.js
  frontend/src/views/main-confirm/factory-detail.js
  frontend/src/views/main-confirm/order-detail.js
  package-lock.json
  package.json
Labels: 백엔드, 기능개발

#243 [feat] 투입산정 insert api 개발 및 validation 체크
  frontend/src/api/CapacityApi.js
  frontend/src/pages/capacity/bar-chart.js
  frontend/src/pages/capacity/index.js
  frontend/src/views/capacity/chart.js
  frontend/src/views/capacity/d3-heat.js
  frontend/src/views/capacity/heat.js
  frontend/src/views/capacity/modal-test.js
Labels: 백엔드, UI/UX, 기능개발

#245 [회원가입/마이페이지]UI변경
  frontend/public/images/login/upload-image-bg-gray.png
  frontend/public/images/login/upload-image-transparent.png
  frontend/public/images/mypage/profile_ract.png
  frontend/public/images/mypage/profile_square.png
  frontend/src/@core/layouts/components/shared-components/UserDropdown.js
  frontend/src/pages/user/login/index.js
  frontend/src/pages/user/register/index.js
  frontend/src/pages/user/userInfo/index.js
Labels: 프론트엔드, UI/UX

#246 [feat]가통코드Popper 새로고침 자연스럽게 완성
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  frontend/src/pages/factory-standard/index.js
  frontend/src/views/factory-standard/possible-detail.js
Labels: 버그, 프론트엔드, UI/UX, 기능개발

#247 [feat] 출강 Lot 셀 별 차트 구현 및 전체 차트 구현
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  frontend/src/pages/lot/index.js
  frontend/src/pages/lot/lot-chart.js
  frontend/src/pages/lot/lot-detail.js
Labels: 프론트엔드, UI/UX, 기능개발

#248 [feat] 필수재 기준 추가 모달 UI 추가
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/entity/EssentialStandard.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/essential-goods/index.js
  frontend/src/pages/index.js
  frontend/src/views/essential-goods/EssentialModal.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX, 기능개발

#249 [Feat] alert, 모달 UI 적용
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/src/api/MainApi.js
  frontend/src/notifix/notiflix-aio.js
  frontend/src/notifix/notiflix-block-aio.js
  frontend/src/notifix/notiflix-confirm-aio.js
  frontend/src/notifix/notiflix-loading-aio.js
  frontend/src/notifix/notiflix-notify-aio.js
  frontend/src/notifix/notiflix-report-aio.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/views/main-confirm/factory-detail.js
Labels: UI/UX, 기능개발

#251 [style]가능/확통기준 알람 스타일 변경
  frontend/src/views/factory-standard/possible-detail.js
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX

#252 [feat] 경유공정 추가 모달 개발
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/ProcessStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/entity/ProcessStandard.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/repository/ProcessStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
  frontend/src/api/PassStandardApi.js
  frontend/src/views/factory-standard/pass-modal-insert.js
  frontend/src/views/factory-standard/pass-modal.js
Labels: 프론트엔드, 백엔드, UI/UX, 기능개발

#257 [FIX] 투입능력산정 에러, 공장결정 API 수정, 가통설계 모달 CSS
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  frontend/src/api/MainApi.js
  frontend/src/pages/capacity/index.js
  frontend/src/views/main-capacity/capacity-modal.js
  frontend/src/views/main-confirm/factory-detail.js
Labels: 버그, UI/UX

#259 [feat] 경유공정기준, 가능확통기준 폴더명 변경
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/ConfirmFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/factory-standard/index.js
  frontend/src/pages/pass-standard/index.js
  frontend/src/pages/process-standard/index.js
  frontend/src/views/pass-standard/confirm-detail.js
  frontend/src/views/pass-standard/pass-modal-insert.js
  frontend/src/views/pass-standard/pass-modal.js
  frontend/src/views/pass-standard/possible-detail.js
Labels: 버그

#262 [feat] 경유공정 추가모달 수정 및 process-standard 파일 삭제
  frontend/src/pages/process-standard/index.js
  frontend/src/views/pass-standard/pass-modal-insert.js
  frontend/src/views/pass-standard/pass-modal.js
Labels: 버그, 프론트엔드, 리팩토링, UI/UX

#263 [bug] build 에러 수정
  frontend/src/pages/lot/index.js
  frontend/src/pages/lot/lot-chart.js
  frontend/src/pages/lot/lot-detail.js
  frontend/src/views/lot/lot-chart.js
  frontend/src/views/lot/lot-detail.js
  frontend/yarn.lock
Labels: 버그, 프론트엔드

#264 [feat] 필수재 기준 필터링 연산자 수정
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/service/EssentialStandardServiceImpl.java
Labels: 백엔드, 기능개발

#265 [feat] 필수재기준 공정계획필수해지적용일자 UI 수정
  frontend/src/views/essential-goods/EssentialModal.js
Labels: 프론트엔드, UI/UX

#266 [feat] 투입산정 api 수정 및 프론트 모달 수정
  backend/src/main/java/com/poscodx/pofect/domain/capacity/controller/CapacityController.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/dto/CapacityInfoDto.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardService.java
  frontend/src/api/CapacityApi.js
  frontend/src/pages/capacity/index.js
Labels: 프론트엔드, 리팩토링, 백엔드, UI/UX, 기능개발

#267 [feat] 사이즈 기준 모달 수정
  backend/build.gradle
  backend/src/main/java/com/poscodx/pofect/common/resttemplate/CustomRestTemplate.java
  backend/src/main/java/com/poscodx/pofect/config/RestTemplateConfig.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/controller/SizeStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/util/RestTemplateTest.java
  frontend/src/pages/lot/lot-detail.js
  frontend/src/pages/size-standard/index.js
  frontend/yarn.lock
Labels: 프론트엔드, 기능개발

#268 [feat] lot-detail 삭제
  frontend/src/pages/lot/lot-detail.js
Labels: 버그, 프론트엔드

#269 [feat] flask rest api 생성
  ai/Pipfile
  ai/Pipfile.lock
  ai/ReadMe.md
  ai/app.py
Labels: 기능개발, AI
