Repository POFECT/Factory-Decision-System, pull requests merged in 2024-01, with the labels that each got.

#273 [feat] 마이페이지 GET API 개발
  backend/src/main/java/com/poscodx/pofect/domain/user/controller/UserController.java
  backend/src/main/java/com/poscodx/pofect/domain/user/dto/UserResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/user/entity/User.java
  backend/src/main/java/com/poscodx/pofect/domain/user/repository/UserRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserService.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
  frontend/src/@core/layouts/components/shared-components/UserDropdown.js
  frontend/src/pages/login&userInfo/userInfo/index.js
Labels: 백엔드, 기능개발

#275 Feat/fe authtest
  ai/ReadMe.md
  ai/app.py
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/_app.js
  frontend/src/pages/api/auth/[...nextauth].js
  frontend/src/pages/api/restricted.js
  frontend/src/pages/login&userInfo/login/index.js
  frontend/src/views/welcome/Welcom.js
  frontend/yarn.lock
Labels: 프론트엔드, 인프라, 기능개발

#277 [fix] user/dto 오류
  backend/src/main/java/com/poscodx/pofect/domain/user/controller/UserController.java
  backend/src/main/java/com/poscodx/pofect/domain/user/dto/UserResDto.java
  backend/src/main/java/com/poscodx/pofect/domain/user/repository/UserRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserService.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
  frontend/src/api/UserApi.js
Labels: 버그

#278 [Feat] APP 주문정보api 생성 및 git merge bug fix
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/FactoryOrderInfoRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/yarn.lock
Labels: UI/UX, 기능개발

#280 [feat] regression modeling
  ai/app.py
Labels: 기능개발, AI

#281 [bug] 출강Lot undefined 해결
  frontend/src/pages/lot/index.js
  frontend/yarn.lock
Labels: 버그, 프론트엔드

#301 [style] 가통popper 그림자 설정 및 모서리 둥글게+ code부분 클릭방지 적용
  frontend/src/pages/pass-standard/index.js
  frontend/src/views/pass-standard/possible-detail.js
Labels: 프론트엔드, UI/UX

#302 [fix]확통 코드 안나오는거 수정
  frontend/src/pages/pass-standard/index.js
Labels: 버그

#303 Feat/dashboard factory capacity
  frontend/src/api/CapacityApi.js
  frontend/src/pages/api/auth/withAuth.js
  frontend/src/pages/capacity/index.js
  frontend/src/pages/index.js
  frontend/src/views/dashboard/FactoryGuage.js
  frontend/src/views/dashboard/HeatMap.js
Labels: 프론트엔드, 기능개발

#304 [feat] 로그 기능 구현
  backend/build.gradle
  backend/src/main/java/com/poscodx/pofect/PofectApplication.java
  backend/src/main/java/com/poscodx/pofect/config/MongoDBConfig.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/repository/CapacityRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityService.java
  backend/src/main/java/com/poscodx/pofect/domain/capacity/service/CapacityServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/log/controller/LogController.java
  backend/src/main/java/com/poscodx/pofect/domain/log/document/CapacityData.java
  backend/src/main/java/com/poscodx/pofect/domain/log/document/ConfirmData.java
  backend/src/main/java/com/poscodx/pofect/domain/log/document/LogDoc.java
  backend/src/main/java/com/poscodx/pofect/domain/log/document/PossibleData.java
  backend/src/main/java/com/poscodx/pofect/domain/log/repository/LogRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/log/service/LogService.java
  backend/src/main/java/com/poscodx/pofect/domain/log/service/LogServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/src/api/LogApi.js
  frontend/src/api/MainApi.js
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/log/index.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/views/log/confirm-modal.js
  frontend/src/views/log/order-data-grid.js
  frontend/src/views/log/order-list.js
  frontend/src/views/log/possible-modal.js
Labels: 프론트엔드, 백엔드, UI/UX, 기능개발

#305 [Feat] fe/pass standard 경유공정모달 수정 및 머지 충돌해결
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/ProcessStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/repository/ProcessStandardRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
  frontend/src/api/ProcessStandardApi.js
  frontend/src/pages/capacity/index.js
  frontend/src/views/pass-standard/pass-modal.js
Labels: 버그, 백엔드, UI/UX, 개발환경 세팅, 기능개발

#306 [feat] weather icon 삭제
  frontend/src/@core/layouts/components/shared-components/ModeToggler.js
  frontend/src/views/dashboard/HeatMap.js
Labels: 프론트엔드, 기능개발

#307 [FEAT] 챗봇 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/avatars/9.png
  frontend/src/pages/_app.js
  frontend/src/pages/api/auth/[...nextauth].js
  frontend/src/pages/size-standard/index.js
  frontend/src/views/chat-bot/ActionProvider.js
  frontend/src/views/chat-bot/BotAvatar.js
  frontend/src/views/chat-bot/ChatBot.js
  frontend/src/views/chat-bot/ChatMessage.js
  frontend/src/views/chat-bot/Layout.js
  frontend/src/views/chat-bot/MessageParser.js
  frontend/src/views/chat-bot/Options.js
  frontend/src/views/chat-bot/QuestionChatBot.js
  frontend/src/views/chat-bot/config.js
  frontend/src/views/pass-standard/pass-modal.js
  frontend/src/views/size-standard/size-design-modal.js
  frontend/styles/chatbot.css
  frontend/yarn.lock
Labels: 프론트엔드, UI/UX, 기능개발

#308 [bug] 로그인 화면에서 챗봇 삭제
  frontend/src/pages/_app.js
Labels: 프론트엔드, UI/UX

#309 [fix]경유공정모달 fix error
  frontend/src/pages/capacity/index.js
  frontend/src/views/capacity/d3-heat.js
  frontend/src/views/pass-standard/pass-modal-insert.js
  frontend/src/views/pass-standard/pass-modal.js
  frontend/yarn.lock
Labels: 버그, 프론트엔드, 백엔드, UI/UX

#310 [feat] 필수재기준 추가 공정에 따른 가통 공장 보여주게 수정
  frontend/src/api/EssentialStandardApi.js
  frontend/src/views/essential-goods/EssentialModal.js
Labels: 프론트엔드, 기능개발

#311 [Feat] 로깅 데이터에 사용자 추가 & CSS 변경
  backend/src/main/java/com/poscodx/pofect/domain/log/document/LogDoc.java
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/dto/FactoryOrderInfoReqDto.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/src/api/MainApi.js
  frontend/src/pages/log/index.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/views/log/confirm-modal.js
  frontend/src/views/log/order-data-grid.js
  frontend/src/views/log/possible-modal.js
  frontend/src/views/main-confirm/order-detail.js
Labels: 프론트엔드, 백엔드, UI/UX

#312 [feat] 필수재기준 추가 시 processCd 한글명 수정
  frontend/src/pages/essential-goods/index.js
  frontend/src/views/essential-goods/EssentialModal.js
Labels: 프론트엔드, 기능개발

#313 [feat]SSE알람 여러개 띄우기 / 알람 title,subtitle분리 / 시간표시(수정예정) / 알림 클릭시 초록 알림표시 삭제
  backend/src/main/java/com/poscodx/pofect/domain/etc/controller/SseController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  backend/src/main/resources/account.yml
  frontend/src/@core/layouts/components/shared-components/NotificationDropdown.js
  frontend/src/@core/layouts/components/shared-components/UserDropdown.js
  frontend/src/pages/_app.js
  frontend/src/pages/user/login/index.js
  frontend/src/views/pages/auth/FooterIllustration.js
  frontend/src/views/pass-standard/possible-detail.js
Labels: 프론트엔드, 백엔드, 기능개발

#314 [fix]필수재기준 품종별 조회 안되는 것 수정
  frontend/src/api/EssentialStandardApi.js
Labels: 버그

#315 [feat] 챗봇 출강주 API 연결 및 데이터 추가
  frontend/src/views/chat-bot/ActionProvider.js
  frontend/src/views/chat-bot/MessageParser.js
  frontend/src/views/chat-bot/QuestionChatBot.js
  frontend/src/views/chat-bot/config.js
Labels: 프론트엔드, 기능개발

#317 [feat] 대시보드 차트 글꼴 수정
  frontend/src/views/dashboard/InputStatusBar.js
  frontend/src/views/dashboard/OrderGrid.js
Labels: 프론트엔드, 기능개발

#318 [fix] 배포를 위한 keycloak endpoint변경
  backend/src/main/java/com/poscodx/pofect/domain/etc/controller/AlertController.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/controller/SseController.java
  backend/src/main/java/com/poscodx/pofect/domain/etc/controller/SseEmitters.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  frontend/src/@core/layouts/components/shared-components/NotificationDropdown.js
  frontend/src/@core/layouts/components/shared-components/UserDropdown.js
  frontend/src/pages/api/auth/[...nextauth].js
Labels: 버그

#323 [feat] 챗봇 에러코드 주문번호 조회 추가
  backend/src/main/java/com/poscodx/pofect/domain/lot/controller/LotController.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotService.java
  backend/src/main/java/com/poscodx/pofect/domain/lot/service/LotServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustom.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/condition/FactoryOrderInfoCondition.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/src/pages/api/LotApi.js
  frontend/src/pages/api/MainApi.js
  frontend/src/views/chat-bot/ActionProvider.js
  frontend/src/views/chat-bot/Options.js
  frontend/src/views/chat-bot/QuestionChatBot.js
  frontend/src/views/chat-bot/config.js
  frontend/src/views/lot/lot-chart.js
  frontend/src/views/lot/lot-detail.js
  frontend/styles/chatbot.css
Labels: 프론트엔드, 기능개발

#325 [feat]DashBoard 히트맵 주별 확통공장 API 및 UI/UX 완료 #324
  backend/src/main/java/com/poscodx/pofect/domain/main/controller/MainController.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/FactoryOrderInfoRepository.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoService.java
  backend/src/main/java/com/poscodx/pofect/domain/main/service/FactoryOrderInfoServiceImpl.java
  frontend/src/pages/api/pofect/MainApi.js
  frontend/src/views/dashboard/HeatMap.js
Labels: 프론트엔드, 백엔드, UI/UX, 기능개발

#326 [feat] 엑셀 컬럼 수정 및 경유공정 버그처리
  frontend/src/pages/capacity/index.js
  frontend/src/views/pass-standard/pass-modal.js
Labels: 버그, 프론트엔드, 백엔드, UI/UX

#327 [feat] mail send 구현
  backend/build.gradle
  backend/src/main/java/com/poscodx/pofect/PofectApplication.java
  backend/src/main/java/com/poscodx/pofect/common/security/config/SecurityConfig.java
  backend/src/main/java/com/poscodx/pofect/domain/user/controller/UserController.java
  backend/src/main/java/com/poscodx/pofect/domain/user/dto/MailSendCode.java
  backend/src/main/java/com/poscodx/pofect/domain/user/dto/MailSendResult.java
  backend/src/main/java/com/poscodx/pofect/domain/user/dto/MimeMessageDto.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/SendMailBatch.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserService.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
  backend/src/main/resources/static/mailForm.html
Labels: 백엔드, 기능개발

#328 [fix] 경유공정 엑셀 컬럼명 변경
  frontend/src/views/pass-standard/pass-modal.js
Labels: 버그, 프론트엔드

#330 [fix] account.yml 삭제
  backend/src/main/resources/account.yml
Labels: 개발환경 세팅

#331 [feat]mail 양식 변경 및 이미지 첨부 기능추가
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/controller/SizeStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/user/controller/UserController.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserService.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
  backend/src/main/resources/static/images/poscodx-email-footer.png
  backend/src/main/resources/static/images/poscodx-email-footer2.png
  backend/src/main/resources/static/mailForm.html
  backend/src/main/resources/templates/mailForm.html
Labels: 백엔드, 기능개발

#332 [feat] yml 파일 암호화
  backend/build.gradle
  backend/src/main/java/com/poscodx/pofect/config/JasyptConfig.java
  backend/src/main/java/com/poscodx/pofect/config/Sha256.java
  backend/src/main/java/com/poscodx/pofect/domain/user/controller/UserController.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
  backend/src/main/resources/application.yml
  frontend/src/pages/_app.js
  frontend/src/pages/size-standard/index.js
  frontend/src/views/chat-bot/ActionProvider.js
  frontend/styles/chatbot.css
Labels: 백엔드, 기능개발

#333 [대시보드] top 대시보드 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/api/pofect/MainApi.js
  frontend/src/views/dashboard/ConfirmDash.js
  frontend/src/views/dashboard/EssentialDash.js
  frontend/src/views/dashboard/HeatMap.js
  frontend/src/views/dashboard/InjectionDash.js
  frontend/src/views/dashboard/PassProcessDash.js
  frontend/src/views/dashboard/SizeDash.js
Labels: 프론트엔드, 기능개발

#334 [feat]메일 기준별 전송 기능 추가 완료
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/controller/EssentialStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/service/EssentialStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/service/EssentialStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/controller/PossibleFactoryStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/controller/ProcessStandardController.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardService.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
  backend/src/main/resources/templates/mailForm.html
  frontend/.env
  frontend/src/pages/api/auth/[...nextauth].js
Labels: 백엔드, 기능개발

#335 Feat/fe 필수재기준 QA
  frontend/src/pages/essential-goods/index.js
  frontend/src/views/dashboard/FactoryGuage.js
  frontend/src/views/essential-goods/EssentialModal.js
Labels: 버그, 프론트엔드

#336 [bug] lotregression api
  frontend/src/pages/api/pofect/api.js
  frontend/src/views/lot-regression/LotRegresion.js
Labels: 버그, 프론트엔드

#337 Feat/fe dashboard qa
  frontend/src/pages/essential-goods/index.js
  frontend/src/views/dashboard/InputStatusBar.js
  frontend/src/views/dashboard/OrderGrid.js
Labels: 버그, 프론트엔드

#338 [fix]가능확통기준 페이지 QA / 이름 양식 석호 포 > 포석호 / NextAuth log 지움
  frontend/src/@core/layouts/components/shared-components/NotificationDropdown.js
  frontend/src/layouts/components/vertical/AppBarContent.js
  frontend/src/pages/api/auth/[...nextauth].js
  frontend/src/pages/api/auth/withAuth.js
  frontend/src/pages/pass-standard/index.js
Labels: 버그, UI/UX

#339 [fix] 경유공정 qa fix
  frontend/src/pages/api/auth/[...nextauth].js
  frontend/src/pages/capacity/index.js
  frontend/src/views/capacity/d3-heat.js
  frontend/src/views/pass-standard/pass-modal-insert.js
  frontend/src/views/pass-standard/pass-modal.js
Labels: 프론트엔드, 백엔드, UI/UX, 개발환경 세팅

#340 [bug] 사이즈, 출강Lot QA
  frontend/src/pages/_app.js
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
  frontend/src/views/chat-bot/config.js
  frontend/src/views/lot/lot-chart.js
  frontend/src/views/lot/lot-detail.js
  frontend/src/views/size-standard/size-design-modal.js
Labels: 프론트엔드, UI/UX

#341 [bug] 필수재기준 추가 모달 수정
  frontend/src/views/essential-goods/EssentialModal.js
Labels: 버그, 프론트엔드

#342 [feat] logo 업로드
  frontend/public/images/pofect_logo.png
  frontend/public/images/pofect_logo2.png
  frontend/public/images/pofect_logo3.png
  frontend/public/images/pofect_logo4.png
  frontend/public/images/pofect_logo5.png
  frontend/public/images/pofect_logo_reverse1.png
  frontend/public/images/pofect_logo_reverse2.png
  frontend/src/@core/layouts/components/vertical/navigation/VerticalNavHeader.js
  frontend/src/pages/_document.js
  frontend/src/pages/user/login/index.js
Labels: 프론트엔드, UI/UX, 디자인

#343 [feat]logo수정
  frontend/public/images/pofect_logo_reverse3.png
  frontend/public/images/pofect_logo_reverse4.png
  frontend/src/@core/layouts/components/vertical/navigation/VerticalNavHeader.js
Labels: 프론트엔드

#344 Bug/fe essential standard
  frontend/src/@core/layouts/components/vertical/navigation/VerticalNavHeader.js
Labels: 프론트엔드, UI/UX

#345 [fix]네비바 단차맞추기
  frontend/src/@core/layouts/components/vertical/navigation/VerticalNavHeader.js
Labels: 버그, UI/UX

#346 [bug] 출강 lot 모달 수정
  frontend/src/pages/lot/index.js
  frontend/src/views/essential-goods/EssentialModal.js
  frontend/src/views/lot-regression/LotRegresion.js
Labels: 버그, 프론트엔드

#347 [fix] 경유공정모달 가로스크롤 해결
  frontend/src/navigation/vertical/index.js
  frontend/src/pages/404.js
  frontend/src/pages/500.js
  frontend/src/pages/user/login/index.js
Labels: 버그, 프론트엔드, UI/UX

#348 [가능/확통기준] Popper 닫기 QA
  frontend/src/pages/pass-standard/index.js
  frontend/src/views/pass-standard/pass-modal-insert.js
Labels: 버그, 프론트엔드

#349 [feat] 경유공정, 투입산정 QA fix 및 앱 대시보드 용 api 추가
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/controller/DashBoardController.java
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/service/DashBoardService.java
  backend/src/main/java/com/poscodx/pofect/domain/dashboard/service/DashBoardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/FactoryOrderInfoRepository.java
  frontend/src/pages/capacity/index.js
  frontend/src/views/capacity/d3-heat.js
  frontend/src/views/pass-standard/pass-modal.js
Labels: 버그, 프론트엔드, 백엔드, 테스트

#350 [출강lot] 에러 수정
  frontend/src/views/lot-regression/LotRegresion.js
Labels: 프론트엔드, 기능개발

#351 Bug/fe essentail modal standard
  frontend/src/pages/essential-goods/index.js
  frontend/src/views/essential-goods/EssentialModal.js
Labels: 버그, 프론트엔드

#352 Bug/fe lot regression
  frontend/src/pages/essential-goods/index.js
  frontend/src/views/essential-goods/EssentialModal.js
  frontend/src/views/lot-regression/LotRegresion.js
Labels: 버그, 프론트엔드

#353 [Feat] 메인, 로그 QA
  frontend/src/pages/capacity/index.js
  frontend/src/pages/log/index.js
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/views/log/possible-modal.js
  frontend/src/views/main-capacity/capacity-detail.js
  frontend/src/views/main-confirm/factory-detail.js
  frontend/src/views/main-confirm/order-detail.js
Labels: 프론트엔드, UI/UX

#354 [feat]경유공정기준 변경 여부 Validation check
  backend/src/main/java/com/poscodx/pofect/config/SwaggerConfig.java
  frontend/src/views/lot-regression/LotRegresion.js
  frontend/src/views/pass-standard/pass-modal.js
Labels: 버그, 프론트엔드, UI/UX

#355 [feat]UserDropdown 로고 POFECT 로고로 변경
  frontend/public/images/mypage/pofect_logo_ract1.png
  frontend/public/images/mypage/pofect_logo_ract2.png
  frontend/src/@core/layouts/components/shared-components/UserDropdown.js
Labels: UI/UX, 디자인

#356 [Feat] Flask 배포
  ai/deploy/.ebignore
  ai/deploy/.gitignore
  ai/deploy/application.py
  ai/deploy/requirements.txt
  frontend/src/pages/log/index.js
  frontend/src/views/log/possible-modal.js
  frontend/src/views/main-capacity/capacity-detail.js
  frontend/src/views/main-confirm/factory-detail.js
Labels: 인프라

#357 [fix] 배포페이지 CSS 오류
  frontend/src/views/main-capacity/capacity-detail.js
Labels: UI/UX

#358 [fix] 투입산정능력 수정 전 저장 막기 & log 삭제
  frontend/src/pages/capacity/index.js
  frontend/src/views/capacity/d3-heat.js
Labels: 버그, 프론트엔드, UI/UX

#359 [feat] logo 원복
  frontend/src/@core/layouts/components/shared-components/UserDropdown.js
Labels: UI/UX

#360 Bug/fe lot regression
  frontend/public/images/spinner.gif
  frontend/src/views/dashboard/EssentialDash.js
  frontend/src/views/dashboard/InjectionDash.js
  frontend/src/views/lot-regression/LotRegresion.js
Labels: 버그, 프론트엔드

#361 [bug] 404, 500 페이지 수정
  frontend/src/pages/404.js
  frontend/src/pages/500.js
Labels: 프론트엔드, 리팩토링

#363 [fix]mail 로그 추가
  backend/src/main/java/com/poscodx/pofect/domain/user/service/SendMailBatch.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
Labels: 백엔드, 테스트

#364 [fix]mail 로그 추가2
  backend/src/main/java/com/poscodx/pofect/domain/user/service/SendMailBatch.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
Labels: 버그, 테스트

#366 [fix]mail 이미지 오류로 인한 양식 변경
  backend/src/main/java/com/poscodx/pofect/domain/user/service/SendMailBatch.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
  backend/src/main/resources/static/images/poscodx-email-footer.png
  backend/src/main/resources/static/images/poscodx-email-footer2.png
  backend/src/main/resources/templates/mailForm.html
Labels: 버그, 백엔드

#367 [feat] 사이즈 기준, Lot QA
  frontend/src/pages/lot/index.js
  frontend/src/pages/size-standard/index.js
  frontend/src/views/chat-bot/config.js
  frontend/src/views/lot/lot-chart.js
Labels: 버그, 프론트엔드

#368 Bug fe/dashboard
  frontend/src/pages/essential-goods/index.js
  frontend/src/views/dashboard/OrderGrid.js
  frontend/src/views/dashboard/SizeDash.js
Labels: 버그, 프론트엔드, 리팩토링, 기능개발

#369 [feat]관리자 pdxx002(혜진) 이메일전송 추가
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/service/EssentialStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
Labels: 백엔드

#370 [fix] 공장변경 후 선택된 주문 유지
  frontend/src/pages/main-confirm/index.js
  frontend/src/views/main-confirm/factory-detail.js
Labels: 버그, 프론트엔드

#371 [fix]Mail 암호화 변경
  backend/src/main/java/com/poscodx/pofect/domain/user/controller/UserController.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/SendMailBatch.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
  backend/src/main/resources/application.yml
Labels: 버그, 백엔드

#373 [feat]Gmail로 변경
  backend/src/main/java/com/poscodx/pofect/domain/essentialstandard/service/EssentialStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/passstandard/service/PossibleFactoryStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/processstandard/service/ProcessStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/sizestandard/service/SizeStandardServiceImpl.java
  backend/src/main/java/com/poscodx/pofect/domain/user/service/SendMailBatch.java
  backend/src/main/resources/templates/mailForm.html
Labels: 버그, 백엔드

#372 [bug] 예측 모달 스크롤 수정
  frontend/src/views/lot-regression/LotRegresion.js
Labels: 버그, 프론트엔드

#377 [fix]이메일 오류 수정 완료
  backend/src/main/java/com/poscodx/pofect/domain/user/service/UserServiceImpl.java
Labels: 버그, 백엔드

#378 [bug] 중복 ord_no 처리
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/FactoryOrderInfoRepository.java
Labels: 버그, 리팩토링, 백엔드

#379 [fix] 공장변경 에러
  frontend/src/pages/main-confirm/index.js
  frontend/src/views/main-confirm/factory-detail.js
  frontend/src/views/main-confirm/order-detail.js
Labels: 버그, 프론트엔드

#380 [bug] 출강주 수정
  frontend/src/pages/essential-goods/index.js
  frontend/src/views/dashboard/FactoryGuage.js
Labels: 버그, 프론트엔드, UI/UX

#381 [bug] 경유공정 기준 페이지 벨리데이션 처리
  frontend/src/views/pass-standard/pass-modal-insert.js
Labels: 버그, 프론트엔드, 백엔드

#382 [Fix] 공장결정 필터링 오류
  frontend/src/pages/main-confirm/index.js
  frontend/src/views/main-confirm/factory-detail.js
Labels: 버그, 프론트엔드

#383 [bug] 공장확정 모달 수정
  frontend/src/pages/main-capacity/index.js
Labels: 버그, 프론트엔드

#384 [fix] 공장변경 에러 해결
  frontend/src/pages/main-confirm/index.js
Labels: 버그, 프론트엔드

#385 Feat fe/main
  frontend/src/views/main-confirm/factory-detail.js
Labels: 버그, UI/UX

#386 [bug] ui 수정
  frontend/src/views/essential-goods/EssentialModal.js
  frontend/src/views/log/confirm-modal.js
  frontend/src/views/log/possible-modal.js
  frontend/src/views/size-standard/size-design-modal.js
Labels: 버그, 프론트엔드

#387 [bug] 필수재 기준 모달 esc 방지하기
  frontend/src/pages/essential-goods/index.js
Labels: 버그, 프론트엔드

#388 [fix] 로딩화면 추가 & select row 오류 & 모달 시간차 문제 & 주문번호 검색 오류
  frontend/src/pages/main-capacity/index.js
  frontend/src/pages/main-confirm/index.js
  frontend/src/views/log/order-list.js
Labels: 버그, 프론트엔드

#389 [fix] A플래그-관리자 이름 삭제
  frontend/src/pages/log/index.js
Labels: 프론트엔드, UI/UX

#390 [fix] 주문 출강주 내림차순으로
  backend/src/main/java/com/poscodx/pofect/domain/main/repository/querydsl/FactoryOrderInfoCustomImpl.java
Labels: 버그, 백엔드
